//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingPlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicTacMatch
    {
        public int IDTable { get; set; }
        public Nullable<int> IDUser1 { get; set; }
        public Nullable<int> IDUser2 { get; set; }
        public Nullable<int> StatusMatch { get; set; }
        public string FEN { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
